/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VacanciesRouteImport } from './routes/vacancies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VacanciesNewRouteImport } from './routes/vacancies.new'
import { Route as VacanciesVacancyIdRouteImport } from './routes/vacancies.$vacancyId'
import { Route as CompaniesNewRouteImport } from './routes/companies.new'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies.$companyId'

const VacanciesRoute = VacanciesRouteImport.update({
  id: '/vacancies',
  path: '/vacancies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VacanciesNewRoute = VacanciesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => VacanciesRoute,
} as any)
const VacanciesVacancyIdRoute = VacanciesVacancyIdRouteImport.update({
  id: '/$vacancyId',
  path: '/$vacancyId',
  getParentRoute: () => VacanciesRoute,
} as any)
const CompaniesNewRoute = CompaniesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => CompaniesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/login': typeof LoginRoute
  '/vacancies': typeof VacanciesRouteWithChildren
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies/new': typeof CompaniesNewRoute
  '/vacancies/$vacancyId': typeof VacanciesVacancyIdRoute
  '/vacancies/new': typeof VacanciesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/login': typeof LoginRoute
  '/vacancies': typeof VacanciesRouteWithChildren
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies/new': typeof CompaniesNewRoute
  '/vacancies/$vacancyId': typeof VacanciesVacancyIdRoute
  '/vacancies/new': typeof VacanciesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/login': typeof LoginRoute
  '/vacancies': typeof VacanciesRouteWithChildren
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies/new': typeof CompaniesNewRoute
  '/vacancies/$vacancyId': typeof VacanciesVacancyIdRoute
  '/vacancies/new': typeof VacanciesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/login'
    | '/vacancies'
    | '/companies/$companyId'
    | '/companies/new'
    | '/vacancies/$vacancyId'
    | '/vacancies/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies'
    | '/login'
    | '/vacancies'
    | '/companies/$companyId'
    | '/companies/new'
    | '/vacancies/$vacancyId'
    | '/vacancies/new'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/login'
    | '/vacancies'
    | '/companies/$companyId'
    | '/companies/new'
    | '/vacancies/$vacancyId'
    | '/vacancies/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  LoginRoute: typeof LoginRoute
  VacanciesRoute: typeof VacanciesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vacancies': {
      id: '/vacancies'
      path: '/vacancies'
      fullPath: '/vacancies'
      preLoaderRoute: typeof VacanciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacancies/new': {
      id: '/vacancies/new'
      path: '/new'
      fullPath: '/vacancies/new'
      preLoaderRoute: typeof VacanciesNewRouteImport
      parentRoute: typeof VacanciesRoute
    }
    '/vacancies/$vacancyId': {
      id: '/vacancies/$vacancyId'
      path: '/$vacancyId'
      fullPath: '/vacancies/$vacancyId'
      preLoaderRoute: typeof VacanciesVacancyIdRouteImport
      parentRoute: typeof VacanciesRoute
    }
    '/companies/new': {
      id: '/companies/new'
      path: '/new'
      fullPath: '/companies/new'
      preLoaderRoute: typeof CompaniesNewRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
  CompaniesNewRoute: typeof CompaniesNewRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
  CompaniesNewRoute: CompaniesNewRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface VacanciesRouteChildren {
  VacanciesVacancyIdRoute: typeof VacanciesVacancyIdRoute
  VacanciesNewRoute: typeof VacanciesNewRoute
}

const VacanciesRouteChildren: VacanciesRouteChildren = {
  VacanciesVacancyIdRoute: VacanciesVacancyIdRoute,
  VacanciesNewRoute: VacanciesNewRoute,
}

const VacanciesRouteWithChildren = VacanciesRoute._addFileChildren(
  VacanciesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  LoginRoute: LoginRoute,
  VacanciesRoute: VacanciesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
